services:
  # Core services
  ultron:
    image: ultron
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ULTRON_SERVER_ADDRESS: ${ULTRON_SERVER_ADDRESS}
      ULTRON_SERVER_REDIS_ADDRESS: ${ULTRON_SERVER_REDIS_ADDRESS}
      ULTRON_SERVER_REDIS_PASSWORD: ${ULTRON_SERVER_REDIS_PASSWORD}
      ULTRON_SERVER_CERTIFICATE_EXPORT_PATH: ${ULTRON_SERVER_CERTIFICATE_EXPORT_PATH}
    networks:
      - ultron
    ports:
      - "8443:8443"
    volumes:
      - ultron_data:/data
    depends_on:
      - redis

  # Auxiliary services
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ultron

volumes:
  ultron_data:
  redis_data:
      
networks:
  ultron: