services:
  # Core services
  ultron:
    image: ultron
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ULTRON_SERVER_ADDRESS: :8443
      ULTRON_REDIS_SERVER_ADDRESS: redis:6379
      ULTRON_SERVER_CERTIFICATE_EXPORT_PATH: /data/cert
    networks:
      - ultron
    ports:
      - "8443:8443"
    volumes:
      - ultron_data:/data
    depends_on:
      - redis

  # Auxiliary services
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ultron
      
networks:
  ultron:

volumes:
  ultron_data:
  redis_data: