name: Go CI

on:
  workflow_dispatch:
    inputs:
      run_docker:
        description: 'Whether to run Docker build and push'
        required: false
        default: 'false'

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Check if Docker steps should run
        id: docker-check
        run: |
          echo "run_docker: ${{ github.event.inputs.run_docker }}"
          if [[ "${{ github.event.inputs.run_docker }}" == "false" ]]; then
            echo "Skipping Docker build and push"
            echo "::set-output name=run_docker::false"
          else
            echo "Running Docker build and push"
            echo "::set-output name=run_docker::true"
          fi

      - name: Set up Docker Buildx
        if: steps.docker-check.outputs.run_docker == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: steps.docker-check.outputs.run_docker == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        if: steps.docker-check.outputs.run_docker == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-go-app:latest

      - name: Push Docker image
        if: steps.docker-check.outputs.run_docker == 'true'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app:latest
